### ISSUE TITLE
v1.2.0 SyntaxError during runtime

### ISSUE THREAD

**Issue by outbounder** [yeliex/node.os#1]
Hi there,

Just letting you know that latest published version (v1.2.0) fails on node 4.x and node 5.x because of the given error:

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

PS. original issue came in from here https://github.com/outbounder/organic-stem-devtools/issues/1 :)

**Comment by yeliex** [comment]
need es6 support
